// ─── VaultKeys Product Catalog ────────────────────────────────────────────────
const STEAM_CDN = 'https://cdn.akamai.steamstatic.com/steam/apps';

const PRODUCTS = [
  // ACTION
  {
    id: 'elden-ring',
    slug: 'elden-ring',
    title: 'Elden Ring',
    subtitle: 'Shadow of the Erdtree Edition',
    category: 'action',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    rating: 4.9,
    reviews: 28412,
    platform: 'PC',
    publisher: 'FromSoftware / Bandai Namco',
    description: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    tags: ['Action RPG', 'Open World', 'Souls-like', 'Dark Fantasy'],
    color: 'from-yellow-900 to-amber-700',
    accent: '#D4A017',
    badge: 'BEST SELLER',
    image: `${STEAM_CDN}/1245620/capsule_616x353.jpg`,
  },
  {
    id: 'doom-eternal',
    slug: 'doom-eternal',
    title: 'DOOM Eternal',
    subtitle: 'Deluxe Edition',
    category: 'action',
    price: 14.99,
    originalPrice: 39.99,
    discount: 62,
    rating: 4.8,
    reviews: 15234,
    platform: 'PC',
    publisher: 'id Software / Bethesda',
    description: 'Experience the ultimate combination of speed and power as you rip and tear through the demonic armies of Hell.',
    tags: ['FPS', 'Action', 'Fast-Paced', 'Gore'],
    color: 'from-red-900 to-orange-700',
    accent: '#FF4500',
    badge: '62% OFF',
    image: `${STEAM_CDN}/782330/capsule_616x353.jpg`,
  },
  {
    id: 'devil-may-cry-5',
    slug: 'devil-may-cry-5',
    title: 'Devil May Cry 5',
    subtitle: 'Special Edition',
    category: 'action',
    price: 12.99,
    originalPrice: 29.99,
    discount: 57,
    rating: 4.7,
    reviews: 9871,
    platform: 'PC',
    publisher: 'Capcom',
    description: 'Three characters. One epic adventure. The most stylish action game ever returns.',
    tags: ['Action', 'Stylish', 'Combat', 'Story-Rich'],
    color: 'from-red-800 to-purple-900',
    accent: '#E53E3E',
    badge: null,
    image: `${STEAM_CDN}/601150/capsule_616x353.jpg`,
  },

  // RPG
  {
    id: 'cyberpunk-2077',
    slug: 'cyberpunk-2077',
    title: 'Cyberpunk 2077',
    subtitle: 'Phantom Liberty Bundle',
    category: 'rpg',
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    rating: 4.6,
    reviews: 41203,
    platform: 'PC',
    publisher: 'CD Projekt Red',
    description: 'An open-world action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.',
    tags: ['Open World', 'RPG', 'Cyberpunk', 'Story-Rich'],
    color: 'from-yellow-600 to-cyan-800',
    accent: '#00FFD4',
    badge: 'HOT',
    image: `${STEAM_CDN}/1091500/capsule_616x353.jpg`,
  },
  {
    id: 'hogwarts-legacy',
    slug: 'hogwarts-legacy',
    title: 'Hogwarts Legacy',
    subtitle: 'Deluxe Edition',
    category: 'rpg',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    rating: 4.5,
    reviews: 33098,
    platform: 'PC',
    publisher: 'Avalanche / Warner Bros',
    description: 'Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart.',
    tags: ['RPG', 'Magic', 'Open World', 'Adventure'],
    color: 'from-purple-900 to-indigo-800',
    accent: '#7C3AED',
    badge: null,
    image: `${STEAM_CDN}/990080/capsule_616x353.jpg`,
  },
  {
    id: 'baldurs-gate-3',
    slug: 'baldurs-gate-3',
    title: "Baldur's Gate 3",
    subtitle: 'Standard Edition',
    category: 'rpg',
    price: 59.99,
    originalPrice: 59.99,
    discount: 0,
    rating: 5.0,
    reviews: 52871,
    platform: 'PC',
    publisher: 'Larian Studios',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.',
    tags: ['RPG', 'Turn-Based', 'DnD', 'Co-op'],
    color: 'from-blue-900 to-violet-900',
    accent: '#6366F1',
    badge: 'GOTY',
    image: `${STEAM_CDN}/1086940/capsule_616x353.jpg`,
  },

  // STRATEGY
  {
    id: 'civilization-vi',
    slug: 'civilization-vi',
    title: 'Sid Meier\'s Civilization VI',
    subtitle: 'Anthology Bundle',
    category: 'strategy',
    price: 24.99,
    originalPrice: 99.99,
    discount: 75,
    rating: 4.6,
    reviews: 19432,
    platform: 'PC',
    publisher: '2K Games / Firaxis',
    description: 'Build an empire to stand the test of time! Explore a new land, research technology, conquer your enemies, and go head-to-head with history\'s greatest leaders.',
    tags: ['Strategy', '4X', 'Turn-Based', 'Historical'],
    color: 'from-green-800 to-emerald-700',
    accent: '#059669',
    badge: '75% OFF',
    image: `${STEAM_CDN}/289070/capsule_616x353.jpg`,
  },
  {
    id: 'total-war-warhammer-3',
    slug: 'total-war-warhammer-3',
    title: 'Total War: WARHAMMER III',
    subtitle: 'Champions of Chaos Edition',
    category: 'strategy',
    price: 34.99,
    originalPrice: 59.99,
    discount: 41,
    rating: 4.4,
    reviews: 12103,
    platform: 'PC',
    publisher: 'Creative Assembly / SEGA',
    description: 'Plunge into a cataclysmic conflict between worlds. Chaos Gods battle for supremacy as the fate of the Old World hangs in the balance.',
    tags: ['Strategy', 'RTS', 'Fantasy', 'Warhammer'],
    color: 'from-gray-800 to-red-900',
    accent: '#991B1B',
    badge: null,
    image: `${STEAM_CDN}/1142710/capsule_616x353.jpg`,
  },

  // SIMULATION
  {
    id: 'stardew-valley',
    slug: 'stardew-valley',
    title: 'Stardew Valley',
    subtitle: '1.6 Update',
    category: 'simulation',
    price: 9.99,
    originalPrice: 13.99,
    discount: 28,
    rating: 4.9,
    reviews: 71023,
    platform: 'PC',
    publisher: 'ConcernedApe',
    description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.',
    tags: ['Farming Sim', 'Relaxing', 'RPG', 'Indie'],
    color: 'from-green-700 to-teal-600',
    accent: '#0D9488',
    badge: 'MUST PLAY',
    image: `${STEAM_CDN}/413150/capsule_616x353.jpg`,
  },
  {
    id: 'cities-skylines-2',
    slug: 'cities-skylines-2',
    title: 'Cities: Skylines II',
    subtitle: 'Ultimate Edition',
    category: 'simulation',
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    rating: 4.2,
    reviews: 8432,
    platform: 'PC',
    publisher: 'Colossal Order / Paradox Interactive',
    description: 'Build the city of your dreams! Bring your urban planning skills and creativity together to craft the most vibrant cities.',
    tags: ['City Builder', 'Simulation', 'Management'],
    color: 'from-sky-800 to-blue-700',
    accent: '#0284C7',
    badge: null,
    image: `${STEAM_CDN}/949230/capsule_616x353.jpg`,
  },

  // INDIE
  {
    id: 'hollow-knight',
    slug: 'hollow-knight',
    title: 'Hollow Knight',
    subtitle: 'Voidheart Edition',
    category: 'indie',
    price: 7.99,
    originalPrice: 14.99,
    discount: 46,
    rating: 4.9,
    reviews: 61234,
    platform: 'PC',
    publisher: 'Team Cherry',
    description: 'A challenging 2D action-adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs.',
    tags: ['Metroidvania', 'Challenging', 'Indie', 'Dark'],
    color: 'from-slate-800 to-indigo-900',
    accent: '#4338CA',
    badge: null,
    image: `${STEAM_CDN}/367520/capsule_616x353.jpg`,
  },
  {
    id: 'hades-2',
    slug: 'hades-2',
    title: 'Hades II',
    subtitle: 'Early Access',
    category: 'indie',
    price: 24.99,
    originalPrice: 24.99,
    discount: 0,
    rating: 4.8,
    reviews: 14521,
    platform: 'PC',
    publisher: 'Supergiant Games',
    description: 'The next rogue-like action game from the creators of the award-winning Hades. Fight beyond the Underworld using dark sorcery.',
    tags: ['Roguelike', 'Action', 'Indie', 'Greek Mythology'],
    color: 'from-purple-800 to-pink-900',
    accent: '#BE185D',
    badge: 'NEW',
    image: `${STEAM_CDN}/1145350/capsule_616x353.jpg`,
  },
  {
    id: 'celeste',
    slug: 'celeste',
    title: 'Celeste',
    subtitle: 'Standard Edition',
    category: 'indie',
    price: 7.99,
    originalPrice: 19.99,
    discount: 60,
    rating: 4.9,
    reviews: 44892,
    platform: 'PC',
    publisher: 'Maddy Makes Games',
    description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain. A challenging precision-platformer with a heartfelt story.',
    tags: ['Platformer', 'Challenging', 'Story-Rich', 'Indie'],
    color: 'from-blue-700 to-pink-700',
    accent: '#EC4899',
    badge: null,
    image: `${STEAM_CDN}/504230/capsule_616x353.jpg`,
  },

  // ACTION (continued)
  {
    id: 'god-of-war',
    slug: 'god-of-war',
    title: 'God of War',
    subtitle: 'PC Edition',
    category: 'action',
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    rating: 4.9,
    reviews: 37820,
    platform: 'PC',
    publisher: 'Santa Monica Studio / PlayStation',
    description: 'His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters.',
    tags: ['Action', 'Adventure', 'Story-Rich', 'Norse Mythology'],
    color: 'from-blue-900 to-slate-700',
    accent: '#3B82F6',
    badge: 'BEST SELLER',
    image: `${STEAM_CDN}/1593500/capsule_616x353.jpg`,
  },
  {
    id: 'red-dead-redemption-2',
    slug: 'red-dead-redemption-2',
    title: 'Red Dead Redemption 2',
    subtitle: 'Ultimate Edition',
    category: 'action',
    price: 29.99,
    originalPrice: 59.99,
    discount: 50,
    rating: 4.9,
    reviews: 44120,
    platform: 'PC',
    publisher: 'Rockstar Games',
    description: 'America, 1899. The end of the wild west era has begun. Outlaws on the run. An epic tale of life in America\'s unforgiving heartland.',
    tags: ['Open World', 'Western', 'Story-Rich', 'Action'],
    color: 'from-amber-900 to-red-900',
    accent: '#B45309',
    badge: null,
    image: `${STEAM_CDN}/1174180/capsule_616x353.jpg`,
  },
  {
    id: 'sekiro',
    slug: 'sekiro',
    title: 'Sekiro: Shadows Die Twice',
    subtitle: 'GOTY Edition',
    category: 'action',
    price: 29.99,
    originalPrice: 59.99,
    discount: 50,
    rating: 4.8,
    reviews: 21043,
    platform: 'PC',
    publisher: 'FromSoftware / Activision',
    description: 'Carve your own path in Sengoku-era Japan. Break the iron code and gain a new perspective on life and death.',
    tags: ['Action', 'Souls-like', 'Stealth', 'Feudal Japan'],
    color: 'from-red-900 to-stone-800',
    accent: '#DC2626',
    badge: 'GOTY',
    image: `${STEAM_CDN}/814380/capsule_616x353.jpg`,
  },
  {
    id: 'resident-evil-4',
    slug: 'resident-evil-4',
    title: 'Resident Evil 4',
    subtitle: 'Remake — Deluxe Edition',
    category: 'action',
    price: 29.99,
    originalPrice: 59.99,
    discount: 50,
    rating: 4.8,
    reviews: 18752,
    platform: 'PC',
    publisher: 'Capcom',
    description: 'Survival horror reimagined. Leon S. Kennedy is sent on a mission to rescue the U.S. President\'s daughter from a mysterious cult.',
    tags: ['Survival Horror', 'Action', 'Remake', 'Story-Rich'],
    color: 'from-green-900 to-gray-900',
    accent: '#16A34A',
    badge: null,
    image: `${STEAM_CDN}/2050650/capsule_616x353.jpg`,
  },
  {
    id: 'monster-hunter-world',
    slug: 'monster-hunter-world',
    title: 'Monster Hunter: World',
    subtitle: 'Iceborne Master Edition',
    category: 'action',
    price: 14.99,
    originalPrice: 29.99,
    discount: 50,
    rating: 4.7,
    reviews: 26410,
    platform: 'PC',
    publisher: 'Capcom',
    description: 'Welcome to the New World! Take on the role of a hunter and slay or capture powerful monsters in a living, breathing ecosystem.',
    tags: ['Action', 'Co-op', 'Hunting', 'Open World'],
    color: 'from-emerald-800 to-teal-900',
    accent: '#059669',
    badge: null,
    image: `${STEAM_CDN}/582010/capsule_616x353.jpg`,
  },

  // RPG (continued)
  {
    id: 'witcher-3',
    slug: 'witcher-3',
    title: 'The Witcher 3: Wild Hunt',
    subtitle: 'Complete Edition',
    category: 'rpg',
    price: 9.99,
    originalPrice: 39.99,
    discount: 75,
    rating: 5.0,
    reviews: 68420,
    platform: 'PC',
    publisher: 'CD Projekt Red',
    description: 'You are Geralt of Rivia, mercenary monster slayer. An epic open-world RPG spanning over 100 hours across war-torn lands.',
    tags: ['RPG', 'Open World', 'Fantasy', 'Story-Rich'],
    color: 'from-yellow-800 to-amber-900',
    accent: '#D97706',
    badge: 'LEGENDARY',
    image: `${STEAM_CDN}/292030/capsule_616x353.jpg`,
  },
  {
    id: 'dark-souls-3',
    slug: 'dark-souls-3',
    title: 'Dark Souls III',
    subtitle: 'Deluxe Edition',
    category: 'rpg',
    price: 14.99,
    originalPrice: 59.99,
    discount: 75,
    rating: 4.8,
    reviews: 31205,
    platform: 'PC',
    publisher: 'FromSoftware / Bandai Namco',
    description: 'The end of fire approaches. Journey through a dark fantasy world, face brutal enemies, and unravel the mystery of the Lords of Cinder.',
    tags: ['Action RPG', 'Souls-like', 'Challenging', 'Dark Fantasy'],
    color: 'from-stone-800 to-neutral-900',
    accent: '#78716C',
    badge: null,
    image: `${STEAM_CDN}/374320/capsule_616x353.jpg`,
  },
  {
    id: 'nier-automata',
    slug: 'nier-automata',
    title: 'NieR: Automata',
    subtitle: 'Game of the YoRHa Edition',
    category: 'rpg',
    price: 12.99,
    originalPrice: 39.99,
    discount: 68,
    rating: 4.9,
    reviews: 29874,
    platform: 'PC',
    publisher: 'PlatinumGames / Square Enix',
    description: 'The distant future. Mankind has been driven from Earth by machine lifeforms. You are 2B — sent to reclaim the world.',
    tags: ['Action RPG', 'Sci-Fi', 'Story-Rich', 'Hack & Slash'],
    color: 'from-zinc-800 to-gray-900',
    accent: '#A1A1AA',
    badge: null,
    image: `${STEAM_CDN}/524220/capsule_616x353.jpg`,
  },

  // STRATEGY (continued)
  {
    id: 'age-of-empires-4',
    slug: 'age-of-empires-4',
    title: 'Age of Empires IV',
    subtitle: 'Anniversary Edition',
    category: 'strategy',
    price: 29.99,
    originalPrice: 59.99,
    discount: 50,
    rating: 4.5,
    reviews: 14032,
    platform: 'PC',
    publisher: 'Relic Entertainment / Xbox',
    description: 'One of the most beloved real-time strategy games returns. Lead major civilizations across history in epic battles.',
    tags: ['RTS', 'Strategy', 'Historical', 'Multiplayer'],
    color: 'from-orange-800 to-yellow-800',
    accent: '#EA580C',
    badge: null,
    image: `${STEAM_CDN}/1466860/capsule_616x353.jpg`,
  },
  {
    id: 'crusader-kings-3',
    slug: 'crusader-kings-3',
    title: 'Crusader Kings III',
    subtitle: 'Royal Edition',
    category: 'strategy',
    price: 19.99,
    originalPrice: 49.99,
    discount: 60,
    rating: 4.7,
    reviews: 16840,
    platform: 'PC',
    publisher: 'Paradox Interactive',
    description: 'Love, fight, scheme, and claim greatness. Expand your dynasty across medieval Europe in the ultimate grand strategy RPG.',
    tags: ['Grand Strategy', 'Medieval', 'Sandbox', 'RPG'],
    color: 'from-red-900 to-amber-800',
    accent: '#B91C1C',
    badge: null,
    image: `${STEAM_CDN}/1158310/capsule_616x353.jpg`,
  },
  {
    id: 'xcom-2',
    slug: 'xcom-2',
    title: 'XCOM 2 Collection',
    subtitle: 'War of the Chosen Bundle',
    category: 'strategy',
    price: 9.99,
    originalPrice: 59.99,
    discount: 83,
    rating: 4.6,
    reviews: 11203,
    platform: 'PC',
    publisher: 'Firaxis / 2K Games',
    description: 'Earth has been lost. Lead a guerrilla war against alien rulers from a mobile base. Every soldier matters — permadeath is real.',
    tags: ['Strategy', 'Turn-Based', 'Sci-Fi', 'Tactical'],
    color: 'from-cyan-900 to-slate-800',
    accent: '#0891B2',
    badge: '83% OFF',
    image: `${STEAM_CDN}/268500/capsule_616x353.jpg`,
  },

  // SIMULATION (continued)
  {
    id: 'planet-zoo',
    slug: 'planet-zoo',
    title: 'Planet Zoo',
    subtitle: 'Ultimate Edition',
    category: 'simulation',
    price: 14.99,
    originalPrice: 44.99,
    discount: 67,
    rating: 4.7,
    reviews: 9214,
    platform: 'PC',
    publisher: 'Frontier Developments',
    description: 'Build and run the zoo of your dreams. Craft detailed habitats, manage your animal collection, and create an extraordinary visitor experience.',
    tags: ['Zoo Management', 'Simulation', 'Building', 'Animals'],
    color: 'from-lime-800 to-green-900',
    accent: '#65A30D',
    badge: null,
    image: `${STEAM_CDN}/703080/capsule_616x353.jpg`,
  },
  {
    id: 'euro-truck-simulator-2',
    slug: 'euro-truck-simulator-2',
    title: 'Euro Truck Simulator 2',
    subtitle: 'Going East! Bundle',
    category: 'simulation',
    price: 9.99,
    originalPrice: 29.99,
    discount: 67,
    rating: 4.8,
    reviews: 42110,
    platform: 'PC',
    publisher: 'SCS Software',
    description: 'Travel across Europe as a king of the road. Drive highly detailed trucks and deliver cargo across a massive open world.',
    tags: ['Driving Sim', 'Relaxing', 'Open World', 'Simulation'],
    color: 'from-blue-800 to-sky-900',
    accent: '#2563EB',
    badge: null,
    image: `${STEAM_CDN}/227300/capsule_616x353.jpg`,
  },
  {
    id: 'farming-simulator-22',
    slug: 'farming-simulator-22',
    title: 'Farming Simulator 22',
    subtitle: 'Platinum Edition',
    category: 'simulation',
    price: 19.99,
    originalPrice: 39.99,
    discount: 50,
    rating: 4.4,
    reviews: 7603,
    platform: 'PC',
    publisher: 'GIANTS Software',
    description: 'Experience farming across three American and European environments. Grow crops, raise livestock, and expand your agricultural empire.',
    tags: ['Farming Sim', 'Relaxing', 'Multiplayer', 'Simulation'],
    color: 'from-yellow-700 to-green-800',
    accent: '#CA8A04',
    badge: null,
    image: `${STEAM_CDN}/1248130/capsule_616x353.jpg`,
  },

  // INDIE (continued)
  {
    id: 'dead-cells',
    slug: 'dead-cells',
    title: 'Dead Cells',
    subtitle: 'Return to Castlevania Edition',
    category: 'indie',
    price: 11.99,
    originalPrice: 24.99,
    discount: 52,
    rating: 4.8,
    reviews: 38901,
    platform: 'PC',
    publisher: 'Motion Twin',
    description: 'A rogue-lite, Metroidvania-inspired action platformer. Explore a sprawling, ever-changing castle and defeat increasingly large bosses.',
    tags: ['Roguelite', 'Metroidvania', 'Action', 'Challenging'],
    color: 'from-orange-800 to-red-800',
    accent: '#EA580C',
    badge: null,
    image: `${STEAM_CDN}/588650/capsule_616x353.jpg`,
  },
  {
    id: 'terraria',
    slug: 'terraria',
    title: 'Terraria',
    subtitle: 'Journey\'s End',
    category: 'indie',
    price: 4.99,
    originalPrice: 9.99,
    discount: 50,
    rating: 4.9,
    reviews: 87340,
    platform: 'PC',
    publisher: 'Re-Logic',
    description: 'Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. 2D sandbox with infinite content.',
    tags: ['Sandbox', '2D', 'Adventure', 'Building'],
    color: 'from-brown-700 to-sky-800',
    accent: '#7C3AED',
    badge: 'MUST PLAY',
    image: `${STEAM_CDN}/105600/capsule_616x353.jpg`,
  },
  {
    id: 'cuphead',
    slug: 'cuphead',
    title: 'Cuphead',
    subtitle: 'The Delicious Last Course',
    category: 'indie',
    price: 11.99,
    originalPrice: 19.99,
    discount: 40,
    rating: 4.8,
    reviews: 26540,
    platform: 'PC',
    publisher: 'Studio MDHR',
    description: 'A classic run and gun action game focused on boss battles. Features the same hand-drawn animation style of the 1930s cartoons.',
    tags: ['Run & Gun', 'Challenging', 'Indie', 'Retro'],
    color: 'from-yellow-600 to-red-700',
    accent: '#DC2626',
    badge: null,
    image: `${STEAM_CDN}/268910/capsule_616x353.jpg`,
  },
  {
    id: 'disco-elysium',
    slug: 'disco-elysium',
    title: 'Disco Elysium',
    subtitle: 'The Final Cut',
    category: 'indie',
    price: 12.99,
    originalPrice: 39.99,
    discount: 68,
    rating: 4.9,
    reviews: 21087,
    platform: 'PC',
    publisher: 'ZA/UM',
    description: 'A groundbreaking open world role playing game. You\'re a detective with a unique skill system at your disposal and a whole city to explore.',
    tags: ['RPG', 'Detective', 'Story-Rich', 'CRPG'],
    color: 'from-violet-900 to-indigo-800',
    accent: '#7C3AED',
    badge: null,
    image: `${STEAM_CDN}/632470/capsule_616x353.jpg`,
  },

  // SHOOTER
  {
    id: 'deep-rock-galactic',
    slug: 'deep-rock-galactic',
    title: 'Deep Rock Galactic',
    subtitle: 'Supporter Edition',
    category: 'shooter',
    price: 14.99,
    originalPrice: 29.99,
    discount: 50,
    rating: 4.9,
    reviews: 48230,
    platform: 'PC',
    publisher: 'Ghost Ship Games',
    description: 'Space Dwarves vs. Bugs. 1-4 player co-op. Mine resources, fight swarms of alien insects, and complete missions deep underground.',
    tags: ['Co-op', 'Shooter', 'Mining', 'PvE'],
    color: 'from-orange-800 to-stone-800',
    accent: '#EA580C',
    badge: 'BEST SELLER',
    image: `${STEAM_CDN}/548430/capsule_616x353.jpg`,
  },
  {
    id: 'back-4-blood',
    slug: 'back-4-blood',
    title: 'Back 4 Blood',
    subtitle: 'Ultimate Edition',
    category: 'shooter',
    price: 14.99,
    originalPrice: 59.99,
    discount: 75,
    rating: 4.4,
    reviews: 12840,
    platform: 'PC',
    publisher: 'Turtle Rock Studios / WB Games',
    description: 'The spiritual successor to Left 4 Dead. Team up with friends to battle hordes of the Ridden in this thrilling co-op shooter.',
    tags: ['Co-op', 'FPS', 'Zombie', 'Horde'],
    color: 'from-red-900 to-zinc-900',
    accent: '#DC2626',
    badge: '75% OFF',
    image: `${STEAM_CDN}/924970/capsule_616x353.jpg`,
  },
  {
    id: 'rainbow-six-siege',
    slug: 'rainbow-six-siege',
    title: 'Tom Clancy\'s Rainbow Six Siege',
    subtitle: 'Deluxe Edition',
    category: 'shooter',
    price: 9.99,
    originalPrice: 19.99,
    discount: 50,
    rating: 4.5,
    reviews: 31450,
    platform: 'PC',
    publisher: 'Ubisoft',
    description: 'Master the art of destruction and gadgetry in Tom Clancy\'s Rainbow Six Siege. A top-tier tactical shooter with unique operators.',
    tags: ['Tactical', 'FPS', 'Multiplayer', 'Competitive'],
    color: 'from-slate-800 to-blue-900',
    accent: '#1D4ED8',
    badge: null,
    image: `${STEAM_CDN}/359550/capsule_616x353.jpg`,
  },
  {
    id: 'payday-2',
    slug: 'payday-2',
    title: 'PAYDAY 2',
    subtitle: 'Crimewave Edition',
    category: 'shooter',
    price: 3.99,
    originalPrice: 9.99,
    discount: 60,
    rating: 4.5,
    reviews: 52100,
    platform: 'PC',
    publisher: 'Overkill Software / Starbreeze',
    description: 'An action-packed co-op shooter where you plan and execute the perfect heist. Bank robberies, drug labs, and more.',
    tags: ['Co-op', 'FPS', 'Heist', 'Stealth'],
    color: 'from-gray-900 to-orange-900',
    accent: '#F97316',
    badge: null,
    image: `${STEAM_CDN}/218620/capsule_616x353.jpg`,
  },
  {
    id: 'insurgency-sandstorm',
    slug: 'insurgency-sandstorm',
    title: 'Insurgency: Sandstorm',
    subtitle: 'Standard Edition',
    category: 'shooter',
    price: 9.99,
    originalPrice: 29.99,
    discount: 67,
    rating: 4.6,
    reviews: 18720,
    platform: 'PC',
    publisher: 'New World Interactive',
    description: 'A hardcore, team-based military shooter with lethal gunplay. Push through enemy territory in intense infantry combat.',
    tags: ['Tactical', 'FPS', 'Military', 'Team-Based'],
    color: 'from-stone-700 to-amber-900',
    accent: '#92400E',
    badge: null,
    image: `${STEAM_CDN}/581320/capsule_616x353.jpg`,
  },

  // BUNDLE
  {
    id: 'vaultkeys-indie-bundle',
    slug: 'vaultkeys-indie-bundle',
    title: 'VaultKeys Indie Bundle',
    subtitle: 'Hollow Knight + Hades II + Celeste',
    category: 'bundle',
    price: 29.99,
    originalPrice: 56.97,
    discount: 47,
    rating: 4.9,
    reviews: 3201,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: '3 award-winning indie masterpieces in one bundle. Save big and get hours of unforgettable gameplay.',
    tags: ['Bundle', 'Value', 'Indie', 'Award-Winning'],
    color: 'from-violet-800 to-fuchsia-800',
    accent: '#A855F7',
    badge: 'BUNDLE DEAL',
    image: `${STEAM_CDN}/367520/capsule_616x353.jpg`,
  },
  {
    id: 'vaultkeys-aaa-bundle',
    slug: 'vaultkeys-aaa-bundle',
    title: 'VaultKeys AAA Bundle',
    subtitle: 'Cyberpunk 2077 + Elden Ring + BG3',
    category: 'bundle',
    price: 79.99,
    originalPrice: 149.97,
    discount: 47,
    rating: 4.9,
    reviews: 1872,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: 'Three of gaming\'s greatest RPG achievements in one massive bundle. 300+ hours of content.',
    tags: ['Bundle', 'AAA', 'RPG', 'Value'],
    color: 'from-orange-800 to-yellow-700',
    accent: '#D97706',
    badge: 'MEGA BUNDLE',
    image: `${STEAM_CDN}/1245620/capsule_616x353.jpg`,
  },
  {
    id: 'vaultkeys-action-bundle',
    slug: 'vaultkeys-action-bundle',
    title: 'VaultKeys Action Bundle',
    subtitle: 'God of War + Elden Ring + RDR2',
    category: 'bundle',
    price: 54.99,
    originalPrice: 139.97,
    discount: 61,
    rating: 4.9,
    reviews: 2104,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: 'Three action masterpieces in one bundle. God of War, Elden Ring, and Red Dead Redemption 2 — 200+ hours of epic gameplay.',
    tags: ['Bundle', 'Action', 'AAA', 'Value'],
    color: 'from-red-800 to-amber-800',
    accent: '#DC2626',
    badge: 'HOT DEAL',
    image: `${STEAM_CDN}/1593500/capsule_616x353.jpg`,
  },
  {
    id: 'vaultkeys-shooter-bundle',
    slug: 'vaultkeys-shooter-bundle',
    title: 'VaultKeys Shooter Bundle',
    subtitle: 'Deep Rock + Back 4 Blood + Rainbow Six',
    category: 'bundle',
    price: 29.99,
    originalPrice: 109.97,
    discount: 73,
    rating: 4.8,
    reviews: 1530,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: 'Three co-op shooter legends in one bundle. Hours of squad-based mayhem at an unbeatable price.',
    tags: ['Bundle', 'Shooter', 'Co-op', 'Value'],
    color: 'from-zinc-800 to-orange-900',
    accent: '#EA580C',
    badge: 'BUNDLE DEAL',
    image: `${STEAM_CDN}/548430/capsule_616x353.jpg`,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null;
}

function getProductsByCategory(category) {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === category);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => ['elden-ring', 'cyberpunk-2077', 'baldurs-gate-3', 'hades-2'].includes(p.slug));
}

function formatPrice(price) {
  return '$' + price.toFixed(2);
}

const CATEGORIES = [
  { id: 'all', label: 'All Games', icon: '🎮' },
  { id: 'action', label: 'Action', icon: '⚔️' },
  { id: 'rpg', label: 'RPG', icon: '🧙' },
  { id: 'strategy', label: 'Strategy', icon: '♟️' },
  { id: 'simulation', label: 'Simulation', icon: '🏙️' },
  { id: 'indie', label: 'Indie', icon: '🌟' },
  { id: 'shooter', label: 'Shooter', icon: '🔫' },
  { id: 'bundle', label: 'Bundles', icon: '📦' },
];
