// ─── VaultKeys Product Catalog ────────────────────────────────────────────────
const STEAM_CDN = 'https://cdn.akamai.steamstatic.com/steam/apps';

const PRODUCTS = [
  // ACTION
  {
    id: 'elden-ring',
    slug: 'elden-ring',
    title: 'Elden Ring',
    subtitle: 'Shadow of the Erdtree Edition',
    category: 'action',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    rating: 4.9,
    reviews: 28412,
    platform: 'PC',
    publisher: 'FromSoftware / Bandai Namco',
    description: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    tags: ['Action RPG', 'Open World', 'Souls-like', 'Dark Fantasy'],
    color: 'from-yellow-900 to-amber-700',
    accent: '#D4A017',
    badge: 'BEST SELLER',
    image: `${STEAM_CDN}/1245620/capsule_616x353.jpg`,
  },
  {
    id: 'doom-eternal',
    slug: 'doom-eternal',
    title: 'DOOM Eternal',
    subtitle: 'Deluxe Edition',
    category: 'action',
    price: 14.99,
    originalPrice: 39.99,
    discount: 62,
    rating: 4.8,
    reviews: 15234,
    platform: 'PC',
    publisher: 'id Software / Bethesda',
    description: 'Experience the ultimate combination of speed and power as you rip and tear through the demonic armies of Hell.',
    tags: ['FPS', 'Action', 'Fast-Paced', 'Gore'],
    color: 'from-red-900 to-orange-700',
    accent: '#FF4500',
    badge: '62% OFF',
    image: `${STEAM_CDN}/782330/capsule_616x353.jpg`,
  },
  {
    id: 'devil-may-cry-5',
    slug: 'devil-may-cry-5',
    title: 'Devil May Cry 5',
    subtitle: 'Special Edition',
    category: 'action',
    price: 12.99,
    originalPrice: 29.99,
    discount: 57,
    rating: 4.7,
    reviews: 9871,
    platform: 'PC',
    publisher: 'Capcom',
    description: 'Three characters. One epic adventure. The most stylish action game ever returns.',
    tags: ['Action', 'Stylish', 'Combat', 'Story-Rich'],
    color: 'from-red-800 to-purple-900',
    accent: '#E53E3E',
    badge: null,
    image: `${STEAM_CDN}/601150/capsule_616x353.jpg`,
  },

  // RPG
  {
    id: 'cyberpunk-2077',
    slug: 'cyberpunk-2077',
    title: 'Cyberpunk 2077',
    subtitle: 'Phantom Liberty Bundle',
    category: 'rpg',
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    rating: 4.6,
    reviews: 41203,
    platform: 'PC',
    publisher: 'CD Projekt Red',
    description: 'An open-world action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.',
    tags: ['Open World', 'RPG', 'Cyberpunk', 'Story-Rich'],
    color: 'from-yellow-600 to-cyan-800',
    accent: '#00FFD4',
    badge: 'HOT',
    image: `${STEAM_CDN}/1091500/capsule_616x353.jpg`,
  },
  {
    id: 'hogwarts-legacy',
    slug: 'hogwarts-legacy',
    title: 'Hogwarts Legacy',
    subtitle: 'Deluxe Edition',
    category: 'rpg',
    price: 49.99,
    originalPrice: 69.99,
    discount: 28,
    rating: 4.5,
    reviews: 33098,
    platform: 'PC',
    publisher: 'Avalanche / Warner Bros',
    description: 'Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart.',
    tags: ['RPG', 'Magic', 'Open World', 'Adventure'],
    color: 'from-purple-900 to-indigo-800',
    accent: '#7C3AED',
    badge: null,
    image: `${STEAM_CDN}/990080/capsule_616x353.jpg`,
  },
  {
    id: 'baldurs-gate-3',
    slug: 'baldurs-gate-3',
    title: "Baldur's Gate 3",
    subtitle: 'Standard Edition',
    category: 'rpg',
    price: 59.99,
    originalPrice: 59.99,
    discount: 0,
    rating: 5.0,
    reviews: 52871,
    platform: 'PC',
    publisher: 'Larian Studios',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.',
    tags: ['RPG', 'Turn-Based', 'DnD', 'Co-op'],
    color: 'from-blue-900 to-violet-900',
    accent: '#6366F1',
    badge: 'GOTY',
    image: `${STEAM_CDN}/1086940/capsule_616x353.jpg`,
  },

  // STRATEGY
  {
    id: 'civilization-vi',
    slug: 'civilization-vi',
    title: 'Sid Meier\'s Civilization VI',
    subtitle: 'Anthology Bundle',
    category: 'strategy',
    price: 24.99,
    originalPrice: 99.99,
    discount: 75,
    rating: 4.6,
    reviews: 19432,
    platform: 'PC',
    publisher: '2K Games / Firaxis',
    description: 'Build an empire to stand the test of time! Explore a new land, research technology, conquer your enemies, and go head-to-head with history\'s greatest leaders.',
    tags: ['Strategy', '4X', 'Turn-Based', 'Historical'],
    color: 'from-green-800 to-emerald-700',
    accent: '#059669',
    badge: '75% OFF',
    image: `${STEAM_CDN}/289070/capsule_616x353.jpg`,
  },
  {
    id: 'total-war-warhammer-3',
    slug: 'total-war-warhammer-3',
    title: 'Total War: WARHAMMER III',
    subtitle: 'Champions of Chaos Edition',
    category: 'strategy',
    price: 34.99,
    originalPrice: 59.99,
    discount: 41,
    rating: 4.4,
    reviews: 12103,
    platform: 'PC',
    publisher: 'Creative Assembly / SEGA',
    description: 'Plunge into a cataclysmic conflict between worlds. Chaos Gods battle for supremacy as the fate of the Old World hangs in the balance.',
    tags: ['Strategy', 'RTS', 'Fantasy', 'Warhammer'],
    color: 'from-gray-800 to-red-900',
    accent: '#991B1B',
    badge: null,
    image: `${STEAM_CDN}/1142710/capsule_616x353.jpg`,
  },

  // SIMULATION
  {
    id: 'stardew-valley',
    slug: 'stardew-valley',
    title: 'Stardew Valley',
    subtitle: '1.6 Update',
    category: 'simulation',
    price: 9.99,
    originalPrice: 13.99,
    discount: 28,
    rating: 4.9,
    reviews: 71023,
    platform: 'PC',
    publisher: 'ConcernedApe',
    description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.',
    tags: ['Farming Sim', 'Relaxing', 'RPG', 'Indie'],
    color: 'from-green-700 to-teal-600',
    accent: '#0D9488',
    badge: 'MUST PLAY',
    image: `${STEAM_CDN}/413150/capsule_616x353.jpg`,
  },
  {
    id: 'cities-skylines-2',
    slug: 'cities-skylines-2',
    title: 'Cities: Skylines II',
    subtitle: 'Ultimate Edition',
    category: 'simulation',
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    rating: 4.2,
    reviews: 8432,
    platform: 'PC',
    publisher: 'Colossal Order / Paradox Interactive',
    description: 'Build the city of your dreams! Bring your urban planning skills and creativity together to craft the most vibrant cities.',
    tags: ['City Builder', 'Simulation', 'Management'],
    color: 'from-sky-800 to-blue-700',
    accent: '#0284C7',
    badge: null,
    image: `${STEAM_CDN}/949230/capsule_616x353.jpg`,
  },

  // INDIE
  {
    id: 'hollow-knight',
    slug: 'hollow-knight',
    title: 'Hollow Knight',
    subtitle: 'Voidheart Edition',
    category: 'indie',
    price: 7.99,
    originalPrice: 14.99,
    discount: 46,
    rating: 4.9,
    reviews: 61234,
    platform: 'PC',
    publisher: 'Team Cherry',
    description: 'A challenging 2D action-adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs.',
    tags: ['Metroidvania', 'Challenging', 'Indie', 'Dark'],
    color: 'from-slate-800 to-indigo-900',
    accent: '#4338CA',
    badge: null,
    image: `${STEAM_CDN}/367520/capsule_616x353.jpg`,
  },
  {
    id: 'hades-2',
    slug: 'hades-2',
    title: 'Hades II',
    subtitle: 'Early Access',
    category: 'indie',
    price: 24.99,
    originalPrice: 24.99,
    discount: 0,
    rating: 4.8,
    reviews: 14521,
    platform: 'PC',
    publisher: 'Supergiant Games',
    description: 'The next rogue-like action game from the creators of the award-winning Hades. Fight beyond the Underworld using dark sorcery.',
    tags: ['Roguelike', 'Action', 'Indie', 'Greek Mythology'],
    color: 'from-purple-800 to-pink-900',
    accent: '#BE185D',
    badge: 'NEW',
    image: `${STEAM_CDN}/1145350/capsule_616x353.jpg`,
  },
  {
    id: 'celeste',
    slug: 'celeste',
    title: 'Celeste',
    subtitle: 'Standard Edition',
    category: 'indie',
    price: 7.99,
    originalPrice: 19.99,
    discount: 60,
    rating: 4.9,
    reviews: 44892,
    platform: 'PC',
    publisher: 'Maddy Makes Games',
    description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain. A challenging precision-platformer with a heartfelt story.',
    tags: ['Platformer', 'Challenging', 'Story-Rich', 'Indie'],
    color: 'from-blue-700 to-pink-700',
    accent: '#EC4899',
    badge: null,
    image: `${STEAM_CDN}/504230/capsule_616x353.jpg`,
  },

  // BUNDLE
  {
    id: 'vaultkeys-indie-bundle',
    slug: 'vaultkeys-indie-bundle',
    title: 'VaultKeys Indie Bundle',
    subtitle: 'Hollow Knight + Hades II + Celeste',
    category: 'bundle',
    price: 29.99,
    originalPrice: 56.97,
    discount: 47,
    rating: 4.9,
    reviews: 3201,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: '3 award-winning indie masterpieces in one bundle. Save big and get hours of unforgettable gameplay.',
    tags: ['Bundle', 'Value', 'Indie', 'Award-Winning'],
    color: 'from-violet-800 to-fuchsia-800',
    accent: '#A855F7',
    badge: 'BUNDLE DEAL',
    image: `${STEAM_CDN}/367520/capsule_616x353.jpg`,
  },
  {
    id: 'vaultkeys-aaa-bundle',
    slug: 'vaultkeys-aaa-bundle',
    title: 'VaultKeys AAA Bundle',
    subtitle: 'Cyberpunk 2077 + Elden Ring + BG3',
    category: 'bundle',
    price: 79.99,
    originalPrice: 149.97,
    discount: 47,
    rating: 4.9,
    reviews: 1872,
    platform: 'PC',
    publisher: 'VaultKeys',
    description: 'Three of gaming\'s greatest RPG achievements in one massive bundle. 300+ hours of content.',
    tags: ['Bundle', 'AAA', 'RPG', 'Value'],
    color: 'from-orange-800 to-yellow-700',
    accent: '#D97706',
    badge: 'MEGA BUNDLE',
    image: `${STEAM_CDN}/1245620/capsule_616x353.jpg`,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null;
}

function getProductsByCategory(category) {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === category);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => ['elden-ring', 'cyberpunk-2077', 'baldurs-gate-3', 'hades-2'].includes(p.slug));
}

function formatPrice(price) {
  return '$' + price.toFixed(2);
}

const CATEGORIES = [
  { id: 'all', label: 'All Games', icon: '🎮' },
  { id: 'action', label: 'Action', icon: '⚔️' },
  { id: 'rpg', label: 'RPG', icon: '🧙' },
  { id: 'strategy', label: 'Strategy', icon: '♟️' },
  { id: 'simulation', label: 'Simulation', icon: '🏙️' },
  { id: 'indie', label: 'Indie', icon: '🌟' },
  { id: 'bundle', label: 'Bundles', icon: '📦' },
];
